name: Sync to GitBook

on:
  push:
    branches:
      - main # 设置为您需要同步的分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install GitBook CLI
      run: npm install -g gitbook-cli

    - name: Build GitBook
      run: |
        gitbook install
        gitbook build

    - name: Publish to GitBook
      env:
        GITBOOK_TOKEN: ${{ secrets.GITBOOK_TOKEN }}
      run: |
        gitbook publish ./ _book --token=$GITBOOK_TOKEN

